"""Proposal layer — Hypothesis generation and Hypothesis→Experiment conversion."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .evolving_framework import Trace
    from .experiment import Experiment
    from .scenario import Scenario


@dataclass
class Hypothesis:
    """A factor hypothesis generated by the Agent.

    Parameters
    ----------
    hypothesis_text : str
        Natural-language description of the factor idea.
    category : str
        Factor taxonomy category (e.g. "momentum", "value").
    data_sources : list[str]
        Tables / data sources the factor needs.
    rationale : str
        Why this hypothesis might work.
    expected_behavior : str
        Expected correlation direction, ideal holding period, etc.
    keywords : list[str]
        Tags for KnowledgeBase retrieval.
    """

    hypothesis_text: str
    category: str
    data_sources: list[str] = field(default_factory=list)
    rationale: str = ""
    expected_behavior: str = ""
    keywords: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "hypothesis_text": self.hypothesis_text,
            "category": self.category,
            "data_sources": self.data_sources,
            "rationale": self.rationale,
            "expected_behavior": self.expected_behavior,
            "keywords": self.keywords,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Hypothesis":
        return cls(**{k: data.get(k, default) for k, default in [
            ("hypothesis_text", ""),
            ("category", ""),
            ("data_sources", []),
            ("rationale", ""),
            ("expected_behavior", ""),
            ("keywords", []),
        ]})


class HypothesisGen(ABC):
    """Abstract base class for hypothesis generation."""

    def __init__(self, scenario: "Scenario") -> None:
        self.scenario = scenario

    @abstractmethod
    def gen(self, trace: "Trace | None" = None) -> Hypothesis:
        """Generate a new hypothesis.

        Parameters
        ----------
        trace : Trace | None
            History of past experiments and feedback.  May be used to
            avoid repeating failed ideas or to build on successes.

        Returns
        -------
        Hypothesis
        """
        raise NotImplementedError


class Hypothesis2Experiment(ABC):
    """Abstract base class for converting a Hypothesis into an Experiment."""

    def __init__(self, scenario: "Scenario") -> None:
        self.scenario = scenario

    @abstractmethod
    def convert(
        self,
        hypothesis: Hypothesis,
        trace: "Trace | None" = None,
    ) -> "Experiment":
        """Convert a hypothesis into an executable experiment.

        For factor research this typically means generating Python code
        with a ``@register`` decorator.

        Parameters
        ----------
        hypothesis : Hypothesis
        trace : Trace | None

        Returns
        -------
        Experiment
        """
        raise NotImplementedError
